language: c

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get install -y git gperf flex bison libncurses5-dev gcc-arm-embedded

script: ./travis_build.sh
